### ISSUE TITLE
仅默认密钥可以正常使用

### ISSUE THREAD

**Issue by Misaka-L** [Sonic853/UdonTotp#1]
如果使用其他密钥的话，生成的一次性密码将会不匹配

![image](https://github.com/Sonic853/UdonTotp/assets/42287372/c3ebcd70-1432-48a7-b947-f425115a70c1)
![image](https://github.com/Sonic853/UdonTotp/assets/42287372/940e6896-5271-4cb7-919b-67b89498bf1a)

**Comment by Sonic853** [comment]
已收到，正在排查问题

**Comment by Sonic853** [comment]
totp-wasm 的前端生成的密钥是直接随机 32 位字符串后直接当做密钥使用，直接随机的 32 位字符串并不是规范的 base32 编码，正常生成密钥时应先随机 20 位字符串再通过 base32 编码为 32 位字符串才能用作密钥使用。目前在分析如何应对非规范的 base32 编码的支持。

**Comment by Sonic853** [comment]
理论 Fixed，请检查
